name: Build WebAssembly module

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false

jobs:
  build-and-test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: python3 -m pip install uv

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        env:
          PIP_BREAK_SYSTEM_PACKAGES: 1
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts
      
      - name: Install dependencies
        working-directory: tools/wasm
        run: npm i

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 'latest'

      - name: Verify Emscripten
        run: emcc -v

      - name: Setup ccache (package)
        if: ${{ inputs.isNightly != true }}
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: wasm-package-${{ runner.os }}-${{ github.ref }}
          max-size: 2G
          restore-keys: |
            wasm-package-${{ runner.os }}-refs/heads/master
            wasm-package-${{ runner.os }}-

      - name: Setup ccache (test)
        if: ${{ inputs.isNightly == true }}
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: wasm-test-${{ runner.os }}-${{ github.ref }}
          max-size: 2G
          restore-keys: |
            wasm-test-${{ runner.os }}-refs/heads/master
            wasm-test-${{ runner.os }}-

      - name: Build WebAssembly package
        working-directory: tools/wasm
        env:
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
        run: |
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: lbug-deploy-wasm
          path: tools/wasm/lbug-wasm.tar.gz

      - name: API test
        working-directory: tools/wasm
        run: npm run test

      - name: Kernel build
        if: ${{ inputs.isNightly == true }}
        env:
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
        run: make wasmtest-build

      - name: Kernel test
        if: ${{ inputs.isNightly == true }}
        run: ctest --test-dir build/wasm/test/ --output-on-failure -j ${TEST_JOBS} --timeout 600

      - name: Kernel test (in memory)
        if: ${{ inputs.isNightly == true }}
        env:
          IN_MEM_MODE: true
        run: ctest --test-dir build/wasm/test/ --output-on-failure -j ${TEST_JOBS} --timeout 600

      - name: Clean up for single-threaded build
        if: ${{ inputs.isNightly == true }}
        run: make clean CMAKE=/usr/bin/cmake

      - name: Setup ccache (single-threaded)
        if: ${{ inputs.isNightly == true }}
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: wasm-test-single-${{ runner.os }}-${{ github.ref }}
          max-size: 2G
          restore-keys: |
            wasm-test-single-${{ runner.os }}-refs/heads/master
            wasm-test-single-${{ runner.os }}-

      - name: Kernel build & test (single-threaded)
        if: ${{ inputs.isNightly == true }}
        env:
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
          SINGLE_THREADED: true
        run: make wasmtest
