name: Build WebAssembly module

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false

jobs:
  build-and-test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: python3 -m pip install uv

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        env:
          PIP_BREAK_SYSTEM_PACKAGES: 1
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts
      
      - name: Install dependencies
        working-directory: tools/wasm
        run: npm i

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 'latest'

      - name: Verify Emscripten
        run: emcc -v

      - name: Build WebAssembly package
        working-directory: tools/wasm
        run: |
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: lbug-deploy-wasm
          path: tools/wasm/lbug-wasm.tar.gz

      - name: API test
        working-directory: tools/wasm
        run: npm run test

      - name: Clean up
        run: make clean

      - name: Kernel build & test
        run: |
          source /home/runner/emsdk/emsdk_env.sh
          make wasmtest

      - name: Kernel build & test in memory
        run: |
          source /home/runner/emsdk/emsdk_env.sh
          make wasmtest
        env:
          IN_MEM_MODE: true

      - name: Kernel build & test (single-threaded)
        env:
          SINGLE_THREADED: true
        run: |
          make clean
          source /home/runner/emsdk/emsdk_env.sh
          make wasmtest
